FROM guergeiro/pnpm:14 as production
WORKDIR /usr/src/app
COPY . .
RUN pnpm install --production

FROM gcr.io/distroless/nodejs:14
WORKDIR /usr/src/app
COPY --from=production /usr/src/app .

CMD ["server.js"]
